Update clashcs

diff --git a/files/bin/clashcs b/files/bin/clashcs
--- a/files/bin/clashcs
+++ b/files/bin/clashcs
@@ -9,115 +9,177 @@
 #   my profile page https://wwww.helmiau.com
 #   my github https://github.com/helmiau
 #--------------------------------------------------------
+
+#-- Warna Teks Installer
+R='\033[1;31m' # Merah Muda
+G='\033[1;32m' # Hijau Muda
+C='\033[0;36m' # Biru Muda
+Y='\033[1;33m' # Kuning
+N='\033[1;37m' # Putih
+
 CORE="/etc/openclash/core/clash"
 ORI="/etc/openclash/core/clash_original"
 PREM="/etc/openclash/core/clash_premium"
 ARCH=$(grep core_version /etc/config/openclash | awk -F"'" '$0=$2')
 #ORILINK=$(curl -sL http://api.github.com/repos/Dreamacro/clash/releases/tags/premium | grep /clash-linux-$1 | sed 's/.*url\": \"//g' | sed 's/\"//g')
 #PREMLINK=$(curl -sL http://api.github.com/repos/vernesong/OpenClash/releases/tags/Clash | grep /clash-linux-$1 | sed 's/.*url\": \"//g' | sed 's/\"//g')
-ORIEXT=".tar.gz -o /tmp/clash.tar.gz"
-PREMEXT=".gz -o /tmp/clash.gz"
+ORIEXT=".tar.gz"
+PREMEXT=".gz"
+CURRENTCORE=$(if [[ -f $CORE ]] && [[ -f $PREM ]]; then echo "Original"; elif [[ -f $CORE ]] && [[ -f $ORI ]]; then echo "Premium";else [[ ! -f $ORI ]] && [[ ! -f $PREM ]] && [[ ! -f $CORE ]]; echo "Unknown"; fi)
 
-echo -e "\033[1;32m"
+
+echo -e "${G}"
 echo "==============================="
 echo "   Clash Core Switcher Script  "
 echo "      Created by helmiau       "
 echo "==============================="
 echo -e "  Architecture : $ARCH"
+echo -e "  Current Core : $CURRENTCORE"
+echo "==============================="
+echo "  Switch to another core : s"
+echo "  Update Premium core    : p"
+echo "  Update Original core   : o"
+echo "  Updt/Install All core  : u"
+echo "  Setup permissions      : c"
+echo "==============================="
+echo -n "  "
+read -r OPT
 
 function helmi_clash_cemod() {
-	chmod +x /etc/openclash/core/clash*
+	echo -e "${Y}"
+	chmod +x $CORE*
+	echo -e "${G}"
 }
 
 function helmi_clash_start() {
+	echo -e "${Y}"
 	/etc/init.d/openclash start
 	uci set openclash.config.enable=1
 	uci commit openclash
+	echo -e "${G}"
 }
 
 function helmi_clash_stop() {
+	echo -e "${Y}"
 	/etc/init.d/openclash stop
 	uci set openclash.config.enable=0
 	uci commit openclash
+	echo -e "${G}"
 }
 
-	echo "==============================="
-if [[ -f $CORE ]] && [[ -f $PREM ]];then
-	echo "  Current Clash Core : Original"
-	echo "  Switch to Premium Core? (y/n)"
-	echo "==============================="
-	echo -n "  "
-	read -r jawab
-	if [[ $jawab == "y" ]]; then
-		helmi_clash_stop \ &&
-		mv /etc/openclash/core/clash /etc/openclash/core/clash_original
-		mv /etc/openclash/core/clash_premium /etc/openclash/core/clash
-		helmi_clash_cemod \ &&
-		helmi_clash_start
+function helmi_switch_premium() {
+	echo -e "${Y}"
+	mv $CORE $ORI
+	mv $PREM $CORE
+	echo -e "${G}"
+}
+
+function helmi_switch_original() {
+	echo -e "${Y}"
+	mv $CORE $PREM
+	mv $ORI $CORE
+	echo -e "${G}"
+}
+
+function helmi_download_premium() {
+	echo -e "${Y}"
+	wget -qO /root/clash-$ARCH$PREMEXT $(curl -L http://api.github.com/repos/Dreamacro/clash/releases/tags/premium | grep /clash-$ARCH | sed 's/.*url\": \"//g' | sed 's/\"//g' | sed 's/https/http/g')
+	echo -e "${G}"
+}
+
+function helmi_download_original() {
+	echo -e "${Y}"
+	wget -qO /root/clash-$ARCH$ORIEXT $(curl -sL http://api.github.com/repos/vernesong/OpenClash/releases/tags/Clash | grep /clash-$ARCH | sed 's/.*url\": \"//g' | sed 's/\"//g' | sed 's/https/http/g')
+	echo -e "${G}"
+}
+
+function helmi_install_premium() {
+	if [[ -s /root/clash-$ARCH$PREMEXT ]]; then
+		echo -e "${G}"
+		gunzip d /root/clash-$ARCH$PREMEXT
+		if [[ $CURRENTCORE = "Original" ]]; then
+			mv /root/clash-$ARCH $PREM
+		else
+			mv /root/clash-$ARCH $CORE
+		fi
+		echo "  Install Done...."
 	else
-		exit
+		echo -e "${R}"
+		echo "  Install Failed...."
+		echo -e "${G}"
 	fi
-elif [[ -f $CORE ]] && [[ -f $ORI ]];then
-	echo "  Current Clash Core : Premium"
-	echo "  Switch to Original Core? (y/n)"
-	echo "==============================="
-	echo -n "  "
-	read -r jawab
-	if [[ $jawab == "y" ]]; then
-		helmi_clash_stop \ &&
-		mv /etc/openclash/core/clash /etc/openclash/core/clash_premium
-		mv /etc/openclash/core/clash_original /etc/openclash/core/clash
-		helmi_clash_cemod \ &&
-		helmi_clash_start
+}
+
+function helmi_install_original() {
+	if [[ -s /root/clash-$ARCH$ORIEXT ]]; then
+		echo -e "${G}"
+		tar xzf /root/clash-$ARCH$ORIEXT -C /root/
+		if [[ $CURRENTCORE = "Premium" ]]; then
+			mv /root/clash $ORI
+			rm -f /root/clash-$ARCH$ORIEXT || true
+		else
+			mv /root/clash $CORE
+			rm -f /root/clash-$ARCH$ORIEXT || true
+		fi
+		echo "  Install Done...."
 	else
-		exit
+		echo -e "${R}"
+		echo "  Install Failed...."
+		echo -e "${G}"
 	fi
-elif [[ -f $CORE ]] && [[ ! -f $PREM ]];then
-	echo "  Current Clash Core = Unknown"
-	echo "  Download Premium Core Now? (y/n)"
-	echo "==============================="
-	echo -n "  "
-	read -r jawab
-	if [[ $jawab == "y" ]]; then
-		helmi_clash_stop \ &&
-		wget -qO- $(curl -sL http://api.github.com/repos/Dreamacro/clash/releases/tags/premium | grep /clash-$ARCH | sed 's/.*url\": \"//g' | sed 's/\"//g') | gunzip -c > /etc/openclash/core/clash
-		wget -qO- $(curl -sL http://api.github.com/repos/vernesong/OpenClash/releases/tags/Clash | grep /clash-$ARCH | sed 's/.*url\": \"//g' | sed 's/\"//g') | tar xOvz > /etc/openclash/core/clash_original
-		helmi_clash_cemod \ &&
-		helmi_clash_start
-	else
-		exit
+}
+
+if [[ $OPT = "s" ]];then
+	helmi_clash_stop \ &&
+	if [[ -f $CORE ]] && [[ -f $PREM ]];then
+		echo "  Switching to Premium Core...."
+		helmi_switch_premium
+	elif [[ -f $CORE ]] && [[ -f $ORI ]];then
+		echo "  Switching to Original Core...."
+		helmi_switch_original
+	elif [[ -f $CORE ]] && [[ ! -f $PREM ]];then
+		echo "  Downloading Premium Core...."
+		helmi_install_premium
+	elif [[ -f $CORE ]] && [[ ! -f $ORI ]];then
+		echo "  Downloading Original Core...."
+		helmi_install_original
+	elif [[ ! -f $ORI ]] && [[ ! -f $PREM ]] && [[ ! -f $CORE ]];then
+		echo "  Downloading Premium Core...."
+		helmi_install_premium
+		echo "  Downloading Original Core...."
+		helmi_install_original
 	fi
-elif [[ -f $CORE ]] && [[ ! -f $ORI ]];then
-	echo "  Current Clash Core = Unknown"
-	echo "  Download Premium Core Now? (y/n)"
-	echo "==============================="
-	echo -n "  "
-	read -r jawab
-	if [[ $jawab == "y" ]]; then
-		helmi_clash_stop \ &&
-		wget -qO- $(curl -sL http://api.github.com/repos/Dreamacro/clash/releases/tags/premium | grep /clash-$ARCH | sed 's/.*url\": \"//g' | sed 's/\"//g') | gunzip -c > /etc/openclash/core/clash
-		wget -qO- $(curl -sL http://api.github.com/repos/vernesong/OpenClash/releases/tags/Clash | grep /clash-$ARCH | sed 's/.*url\": \"//g' | sed 's/\"//g') | tar xOvz > /etc/openclash/core/clash_original
-		helmi_clash_cemod \ &&
-		helmi_clash_start
-	else
-		exit
-	fi
-elif [[ ! -f $ORI ]] && [[ ! -f $PREM ]] && [[ ! -f $CORE ]];then
-	echo "  Current Clash Core = Unknown"
-	echo "  Download Premium Core Now? (y/n)"
-	echo "==============================="
-	echo -n "  "
-	read -r jawab
-	if [[ $jawab == "y" ]]; then
-		helmi_clash_stop \ &&
-		wget -qO- $(curl -sL http://api.github.com/repos/Dreamacro/clash/releases/tags/premium | grep /clash-$ARCH | sed 's/.*url\": \"//g' | sed 's/\"//g') | gunzip -c > /etc/openclash/core/clash
-		wget -qO- $(curl -sL http://api.github.com/repos/vernesong/OpenClash/releases/tags/Clash | grep /clash-$ARCH | sed 's/.*url\": \"//g' | sed 's/\"//g') | tar xOvz > /etc/openclash/core/clash_original
-		helmi_clash_cemod \ &&
-		helmi_clash_start
-	else
-		exit
-	fi
+elif [[ $OPT = "p" ]];then
+	echo "  Downloading Premium Core...."
+	helmi_download_premium
+	echo "  Installing Premium Core...."
+	helmi_install_premium
+elif [[ $OPT = "o" ]];then
+	echo "  Downloading Original Core...."
+	helmi_download_original
+	echo "  Installing Original Core...."
+	helmi_install_original
+elif [[ $OPT = "u" ]];then
+	echo "  Downloading Premium Core...."
+	helmi_download_premium
+	echo "  Installing Premium Core...."
+	helmi_install_premium
+	echo "  Downloading Original Core...."
+	helmi_download_original
+	echo "  Installing Original Core...."
+	helmi_install_original
+elif [[ $OPT = "c" ]];then
+	echo "  Configuring permissions...."
+	helmi_clash_cemod
+	helmi_clash_start
+	echo "  Done...."
 else
-	echo "  Exiting bro. see yu suun !"
+	echo " Exiting...."
+	helmi_clash_cemod
+	helmi_clash_start
 	exit
 fi
+echo "==============================="
+
+helmi_clash_cemod
+helmi_clash_start
