clashcs v2.5
Add : TUN, Game core installer script
Add : Openclash ipk installer
Add : Curent openclash version

diff --git a/files/bin/clashcs b/files/bin/clashcs
--- a/files/bin/clashcs
+++ b/files/bin/clashcs
@@ -18,6 +18,8 @@ Y='\033[1;33m' # Kuning
 N='\033[1;37m' # Putih
 
 CORE="/etc/openclash/core/clash"
+TUN="/etc/openclash/core/clash_tun"
+GAME="/etc/openclash/core/clash_game"
 ORI="/etc/openclash/core/clash_original"
 PREM="/etc/openclash/core/clash_premium"
 ARCH=$(grep core_version /etc/config/openclash | awk -F"'" '$0=$2')
@@ -26,21 +28,36 @@ ARCH=$(grep core_version /etc/config/openclash | awk -F"'" '$0=$2')
 ORIEXT=".tar.gz"
 PREMEXT=".gz"
 CURRENTCORE=$(if [[ -f $CORE ]] && [[ -f $PREM ]]; then echo "Original"; elif [[ -f $CORE ]] && [[ -f $ORI ]]; then echo "Premium";else [[ ! -f $ORI ]] && [[ ! -f $PREM ]] && [[ ! -f $CORE ]]; echo "Unknown"; fi)
-
+IPKVER=$(opkg list-installed | grep luci-app-openclash | sed -e 's/luci-app-openclash - //g' )
+IPKSTAT=$(if [[ $IPKVER == *"."* ]]; then echo "Installed";else echo "Not Available"; fi)
+#wget $(curl -sL https://github.com/vernesong/OpenClash/releases | grep luci-app-openclash_ | sed -e 's/\"//g' -e 's/ //g' -e 's/rel=.*//g' -e 's#<ahref=#http://github.com#g' | awk 'FNR <= 1')
+SCRIPTVER="2.5"
 
 echo -e "${G}"
 echo "==============================="
-echo "   Clash Core Switcher Script  "
-echo "      Created by helmiau       "
+echo "     OpenClash Manager v$SCRIPTVER"
+echo "      Created by helmiau"
 echo "==============================="
-echo -e "  Architecture : $ARCH"
-echo -e "  Current Core : $CURRENTCORE"
+echo -e "  Architecture  : $ARCH"
+echo -e "  Current Core  : $CURRENTCORE"
+echo -e "  OpenClash App : $IPKSTAT"
+echo -e "  App Version   : $IPKVER"
 echo "==============================="
-echo "  Switch to another core : s"
-echo "  Update Premium core    : p"
-echo "  Update Original core   : o"
-echo "  Updt/Install All core  : u"
-echo "  Setup permissions      : c"
+if [[ $CURRENTCORE = "Original" ]]; then
+	echo "  Switch to Premium core : s"
+elif [[ $CURRENTCORE = "Premium" ]]; then
+	echo "  Switch to Origin core  : s"
+else
+	echo "  Install all cores      : s"
+fi
+echo "  Inst/Upd Premium core  : p"
+echo "  Inst/Upd Original core : o"
+echo "  Inst/Upd TUN core      : t"
+echo "  Inst/Upd Game core     : g"
+echo "  Inst/Upd all cores     : u"
+echo "  Inst/Upd OpenClash App : a"
+echo "  Start OpenClash        : c"
+echo "  Stop OpenClash         : h"
 echo "==============================="
 echo -n "  "
 read -r OPT
@@ -93,6 +110,24 @@ function helmi_download_original() {
 	echo -e "${G}"
 }
 
+function helmi_download_tun() {
+	echo -e "${Y}"
+	wget -qO /root/clash-tun-$ARCH$ORIEXT $(curl -sL http://api.github.com/repos/vernesong/OpenClash/releases/tags/TUN-Premium | grep /clash-$ARCH | sed 's/.*url\": \"//g' | sed 's/\"//g' | sed 's/https/http/g')
+	echo -e "${G}"
+}
+
+function helmi_download_game() {
+	echo -e "${Y}"
+	wget -qO /root/clash-game-$ARCH$ORIEXT $(curl -sL http://api.github.com/repos/vernesong/OpenClash/releases/tags/TUN | grep /clash-$ARCH | sed 's/.*url\": \"//g' | sed 's/\"//g' | sed 's/https/http/g')
+	echo -e "${G}"
+}
+
+function helmi_download_ipk() {
+	echo -e "${Y}"
+	wget -qO /root/luci-app-openclash.ipk $(curl -sL https://github.com/vernesong/OpenClash/releases | grep luci-app-openclash_ | sed -e 's/\"//g' -e 's/ //g' -e 's/rel=.*//g' -e 's#<ahref=#http://github.com#g' | awk 'FNR <= 1')
+	echo -e "${G}"
+}
+
 function helmi_install_premium() {
 	if [[ -s /root/clash-$ARCH$PREMEXT ]]; then
 		echo -e "${G}"
@@ -102,10 +137,10 @@ function helmi_install_premium() {
 		else
 			mv /root/clash-$ARCH $CORE
 		fi
-		echo "  Install Done...."
+		echo "  Premium Core Install Done...."
 	else
 		echo -e "${R}"
-		echo "  Install Failed...."
+		echo "  Premium Core Install Failed...."
 		echo -e "${G}"
 	fi
 }
@@ -122,6 +157,47 @@ function helmi_install_original() {
 			rm -f /root/clash-$ARCH$ORIEXT || true
 		fi
 		echo "  Install Done...."
+	else
+		echo -e "${R}"
+		echo "  Install Failed...."
+		echo -e "${G}"
+	fi
+}
+
+function helmi_install_tun() {
+	if [[ -s /root/clash-$ARCH$ORIEXT ]]; then
+		echo -e "${G}"
+		tar xzf /root/clash-$ARCH$ORIEXT -C /root/
+		mv /root/clash $TUN
+		rm -f /root/clash-$ARCH$ORIEXT || true
+		echo "  TUN Core Install Done...."
+	else
+		echo -e "${R}"
+		echo "  TUN Core Install Failed...."
+		echo -e "${G}"
+	fi
+}
+
+function helmi_install_game() {
+	if [[ -s /root/clash-game-$ARCH$ORIEXT ]]; then
+		echo -e "${G}"
+		tar xzf /root/clash-game-$ARCH$ORIEXT -C /root/
+		mv /root/clash $GAME
+		rm -f /root/clash-game-$ARCH$ORIEXT || true
+		echo "  Game Core Install Done...."
+	else
+		echo -e "${R}"
+		echo "  Game Core Install Failed...."
+		echo -e "${G}"
+	fi
+}
+
+function helmi_install_ipk() {
+	if [[ -s /root/luci-app-openclash.ipk ]]; then
+		echo -e "${G}"
+		opkg install /root/luci-app-openclash.ipk
+		rm -f /root/luci-app-openclash.ipk || true
+		echo "  App Install Done...."
 	else
 		echo -e "${R}"
 		echo "  Install Failed...."
@@ -159,6 +235,24 @@ elif [[ $OPT = "o" ]];then
 	helmi_download_original
 	echo "  Installing Original Core...."
 	helmi_install_original
+elif [[ $OPT = "t" ]];then
+	echo "  Downloading TUN Core...."
+	helmi_download_tun
+	echo "  Installing TUN Core...."
+	helmi_install_tun
+elif [[ $OPT = "g" ]];then
+	echo "  Downloading Game Core...."
+	helmi_download_game
+	echo "  Installing Game Core...."
+	helmi_install_game
+elif [[ $OPT = "h" ]];then
+	echo "  Stopping OpenClash...."
+	helmi_clash_stop
+elif [[ $OPT = "i" ]];then
+	echo "  Downloading OpenClash App...."
+	helmi_download_ipk
+	echo "  Installing OpenClash App...."
+	helmi_install_ipk
 elif [[ $OPT = "u" ]];then
 	echo "  Downloading Premium Core...."
 	helmi_download_premium
@@ -168,18 +262,34 @@ elif [[ $OPT = "u" ]];then
 	helmi_download_original
 	echo "  Installing Original Core...."
 	helmi_install_original
+	echo "  Downloading TUN Core...."
+	helmi_download_tun
+	echo "  Installing TUN Core...."
+	helmi_install_tun
+	echo "  Downloading Game Core...."
+	helmi_download_game
+	echo "  Installing Game Core...."
+	helmi_install_game
 elif [[ $OPT = "c" ]];then
 	echo "  Configuring permissions...."
 	helmi_clash_cemod
+	echo "  Starting Clash...."
 	helmi_clash_start
 	echo "  Done...."
+	exit
 else
-	echo " Exiting...."
+	echo "  Configuring permissions...."
 	helmi_clash_cemod
+	echo "  Starting Clash...."
 	helmi_clash_start
+	echo "  Done...."
+	echo "  Exiting...."
 	exit
 fi
 echo "==============================="
 
+echo "  Configuring permissions...."
 helmi_clash_cemod
+echo "  Starting Clash...."
 helmi_clash_start
+echo "==============================="
